version: '3.8'

services:
  fleet-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge