name: Deploy to EC2

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/vehicle-inventory && git checkout master && git pull && docker build -t vehicle-inventory-app .
            cd ~/fleet-manager && git checkout develop && git pull && docker build -t fleet-manager-app .
            cd ~/ && docker-compose down && docker-compose up -d